version: "3"
services:
  springapp:
    image: dockerhandson/spring-boot-mongo
    ports:
    - "8080:8080"
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        max_attempts: 5
  mongo:
    image: mongo
    volumes:
    - "mongodbbkp:/data/db"
volumes:
  mongodbbkp:
    external: true
networks:
  default:
    external:
      name: airtel
        
